# Copyright (c) 2025 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//luxxle/build/config.gni")
# Commented out: removed components dependency - using Chromium defaults instead
import("//build/config/features.gni")
import("//chrome/common/features.gni")

source_set("brave_browser_command") {
  sources = [
    "brave_browser_command_handler.cc",
    "brave_browser_command_handler.h",
  ]

  deps = [
    "//base:base",
    "//luxxle/browser/ai_chat",
    # REMOVED: "//luxxle/browser/brave_rewards",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/brave_education",
    # Commented out: removed components dependency - using Chromium defaults instead
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/constants",
    "//luxxle/ui/webui/resources/js/brave_browser_command:mojo_bindings",
    "//chrome/browser/profiles:profile",
    "//mojo/public/cpp/bindings:bindings",
    "//ui/base:types",
    "//url:url",
  ]

  }
}
