# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_browser_prefs_deps = [
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_ads/core",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_news/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_rewards/core",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_shields/core/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_sync:prefs",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_wallet/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/de_amp/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/debounce/core/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/decentralized_dns/core",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/ntp_background_images/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/p3a",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/p3a:buildflags",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/skus/browser",
  "//luxxle/ios/browser/brave_stats",
]
