# Copyright (c) 2025 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Minimal policy definitions override for Luxxle - use Chromium defaults
# This file is imported by components/policy/BUILD.gn

# Define empty policy variables to use Chromium defaults
brave_generate_policy_templates_inputs = [] 