# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/. */

# Commented out: removed components dependency - using Chromium defaults instead
# import("//luxxle/components/playlist/common/buildflags/buildflags.gni")

brave_browser_playlist_sources = []
brave_browser_playlist_deps = []

if (enable_playlist) {
  brave_browser_playlist_sources += [
    "//luxxle/browser/playlist/playlist_service_factory.cc",
    "//luxxle/browser/playlist/playlist_service_factory.h",
  ]

  brave_browser_playlist_deps += [
    "//base",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/playlist/browser",
    "//chrome/browser:browser_process",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/keyed_service/content",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/pref_registry:pref_registry",
  ]

  if (is_android) {
    brave_browser_playlist_sources += [
      "//luxxle/browser/playlist/android/playlist_service_factory_android.cc",
    ]

    brave_browser_playlist_deps += [
      "//luxxle/build/android:jni_headers",
      "//mojo/public/cpp/bindings",
    ]
  } else {
    brave_browser_playlist_sources += [
      "//luxxle/browser/playlist/playlist_data_source.cc",
      "//luxxle/browser/playlist/playlist_data_source.h",
    ]
  }
}
