browser_api_opentabs_public_headers = [
  "//luxxle/ios/browser/api/opentabs/luxxle_opentabs_api.h",
  "//luxxle/ios/browser/api/opentabs/luxxle_opentabs_observer.h",
  "//luxxle/ios/browser/api/opentabs/luxxle_sendtab_api.h",
  "//luxxle/ios/browser/api/opentabs/luxxle_sendtab_observer.h",
  "//luxxle/ios/browser/api/opentabs/luxxle_tabgenerator_api.h",
]
