# Copyright (c) 2025 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Commented out: transpile_web_ui function requires Luxxle components that have been removed
# Email aliases functionality disabled for Luxxle minimal build

# import("//luxxle/components/common/typescript.gni")

# transpile_web_ui("email_aliases_ui") {
#   generate_grdp = true
#
#   entry_points = [ [
#         "email_aliases",
#         rebase_path("email_aliases.tsx"),
#       ] ]
#
#   resource_name = "email_aliases"
#
#   # Commented out: removed components dependency - using Chromium defaults instead
#   # deps = [ "//luxxle/components/email_aliases:mojom_js" ]
# }
