# Copyright (c) 2020 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

source_set("models") {
  sources = [
    "luxxle_certificate_enums.h",
    "luxxle_certificate_fingerprint.h",
    "luxxle_certificate_fingerprint.mm",
    "luxxle_certificate_model+private.h",
    "luxxle_certificate_public_key_info.h",
    "luxxle_certificate_public_key_info.mm",
    "luxxle_certificate_rdns_sequence.h",
    "luxxle_certificate_rdns_sequence.mm",
    "luxxle_certificate_signature.h",
    "luxxle_certificate_signature.mm",
  ]

  deps = [
    "//base",
    "//luxxle/base/mac",
    "//luxxle/ios/browser/api/certificate/utils",
    "//luxxle/ios/browser/api/common",
    "//crypto",
    "//net",
    "//third_party/abseil-cpp:absl",
    "//third_party/boringssl",
  ]

  frameworks = [
    "Foundation.framework",
    "Security.framework",
  ]
}
