# Copyright (c) 2023 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Commented out: removed components dependency - using Chromium defaults instead
# Commented out: removed components dependency - using Chromium defaults instead
# import("//luxxle/components/web_discovery/buildflags/buildflags.gni")
# Commented out: removed components dependency - using Chromium defaults instead
# import("//luxxle/components/webcompat_reporter/buildflags/buildflags.gni")
import("//build/config/android/rules.gni")

declare_args() {
  luxxle_android_developer_options_code = ""
}

java_cpp_enum("luxxle_android_java_enums_srcjar") {
  sources = [
    "//luxxle/chromium_src/chrome/browser/notifications/notification_handler_impl.h",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/decentralized_dns/core/constants.h",
  ]
}

java_cpp_template("luxxle_config_java") {
  sources = [ "//luxxle/build/android/java/templates/LuxxleConfig.template" ]
  defines = [
    "LUXXLE_ANDROID_DEVELOPER_OPTIONS_CODE=\"$luxxle_android_developer_options_code\"",
    "LUXXLE_ANDROID_WEBCOMPAT_REPORT_ENDPOINT=\"$webcompat_report_api_endpoint\"",
    "LUXXLE_ANDROID_WEB_DISCOVERY_ENABLED=$enable_web_discovery_native",
  ]
}
