# Copyright (c) 2024 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

luxxle_browser_renderer_context_menu_sources = []
luxxle_browser_renderer_context_menu_deps = []

if (is_win || is_linux) {
  luxxle_browser_renderer_context_menu_sources += [
    "//luxxle/browser/renderer_context_menu/luxxle_spelling_options_submenu_observer.cc",
    "//luxxle/browser/renderer_context_menu/luxxle_spelling_options_submenu_observer.h",
  ]

  luxxle_browser_renderer_context_menu_deps += [
    "//base",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/renderer_context_menu",
    "//ui/base",
  ]
}
