# Copyright (c) 2023 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

luxxle_browser_onboarding_sources = [
  "//luxxle/browser/onboarding/onboarding_tab_helper.cc",
  "//luxxle/browser/onboarding/onboarding_tab_helper.h",
  "//luxxle/browser/onboarding/pref_names.h",
]

luxxle_browser_onboarding_deps = [
  "//base",
  "//luxxle/browser:browser_process",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/content_settings/core/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/content_settings/core/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/permissions",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/pref_registry",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/prefs",
  "//content/public/browser",
]
