# Copyright (c) 2025 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

luxxle_tab_search_extras_grdp = "$root_gen_dir/luxxle/browser/resources/tab_search/luxxle_extras.grdp"

luxxle_tab_search_static_files = [
  "luxxle/tab_organizer_illustration.svg",
  # SVG and other static files
]

# Here we could also define any .ts in relevant variables
# e.g. luxxle_tab_search_web_component_files and luxxle_tab_search_non_web_component_files
# when we have the need for them.

luxxle_tab_search_extra_grdp_files = [ luxxle_tab_search_extras_grdp ]

luxxle_tab_search_extra_grdp_deps = [ "//luxxle/browser/resources/tab_search:static_files" ]
