# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_flags_deps = [
  "//base",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_ads/core",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_component_updater/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_rewards/core",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_rewards/core/buildflags",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_shields/core/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_user_agent/common:common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/brave_wallet/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/de_amp/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/debounce/core/common",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/ntp_background_images/browser",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//luxxle/components/skus/common",
  "//luxxle/ios/browser/playlist",
  "//luxxle/ios/browser/ui/browser_menu:features",
  "//luxxle/ios/browser/ui/web_view:features",
  # Commented out: removed components dependency - using Chromium defaults instead
  # "//components/webui/flags",
  "//net",
]
