# Copyright (c) 2021 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//luxxle/components/luxxle_vpn/common/buildflags/buildflags.gni")

luxxle_chromium_src_chrome_test_test_support_sources = [
  "//luxxle/test/base/testing_luxxle_browser_process.cc",
  "//luxxle/test/base/testing_luxxle_browser_process.h",
]

luxxle_chromium_src_chrome_test_test_support_deps = [
  "//luxxle/components/ai_chat/core/browser:test_support",
  "//luxxle/components/luxxle_shields/content/browser",
  "//luxxle/components/luxxle_shields/content/browser:test_support",
  "//luxxle/components/luxxle_vpn/common/buildflags",
  "//luxxle/components/tor/buildflags",
]

if (enable_luxxle_vpn) {
  luxxle_chromium_src_chrome_test_test_support_deps +=
      [ "//luxxle/components/luxxle_vpn/browser/connection:api" ]
}
