/* Copyright (c) 2022 The Luxxle Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "luxxle/browser/themes/luxxle_private_window_theme_supplier.h"

#include "luxxle/browser/ui/color/luxxle_color_mixer.h"
#include "luxxle/browser/ui/tabs/luxxle_tab_color_mixer.h"
#include "ui/color/color_provider_key.h"

LuxxlePrivateWindowThemeSupplier::LuxxlePrivateWindowThemeSupplier(
    bool private_window)
    : CustomThemeSupplier(ThemeType::kAutogenerated),
      for_private_window_(private_window) {}

LuxxlePrivateWindowThemeSupplier::~LuxxlePrivateWindowThemeSupplier() = default;

void LuxxlePrivateWindowThemeSupplier::AddColorMixers(
    ui::ColorProvider* provider,
    const ui::ColorProviderKey& key) const {
  if (for_private_window_) {
    AddPrivateThemeColorMixer(provider, key);
    tabs::AddLuxxleTabPrivateThemeColorMixer(provider, key);
  } else {
    AddTorThemeColorMixer(provider, key);
    tabs::AddLuxxleTabTorThemeColorMixer(provider, key);
  }
  // Private/Tor uses same omnibox colors.
  AddLuxxleOmniboxPrivateThemeColorMixer(provider, key);
}
