# Copyright (c) 2023 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

source_set("unit_tests") {
  testonly = true
  assert(is_win || is_linux || is_mac)
  sources = [ "render_view_context_menu_unittest.cc" ]
  deps = [
    "//base",
    "//luxxle/app:command_ids",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/ai_chat/core/common",
    "//chrome/browser",
    "//chrome/browser/search_engines",
    "//chrome/test:test_support",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/custom_handlers",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/custom_handlers:test_support",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//components/search_engines",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/abseil-cpp:absl",
  ]
}
