# Copyright (c) 2025 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# Minimal common sources override for Luxxle - use Chromium defaults
# This file provides variables for chrome/common/BUILD.gn

# Define empty chrome common variables to use Chromium defaults
luxxle_chrome_common_sources = []
luxxle_chrome_common_deps = []
luxxle_chrome_common_public_deps = []
