# Copyright (c) 2020 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//extensions/buildflags/buildflags.gni")

luxxle_browser_importer_sources = []
luxxle_browser_importer_public_deps = []
luxxle_browser_importer_impl_sources = []
luxxle_browser_importer_impl_deps = []

if (!is_android) {
  luxxle_browser_importer_sources +=
      [ "//luxxle/browser/importer/luxxle_external_process_importer_host.h" ]
  luxxle_browser_importer_public_deps += [
    "//base",
    "//chrome/common/extensions",
    "//extensions/buildflags",
  ]
  luxxle_browser_importer_impl_sources += [
    "//luxxle/browser/importer/luxxle_external_process_importer_client.cc",
    "//luxxle/browser/importer/luxxle_external_process_importer_client.h",
    "//luxxle/browser/importer/luxxle_external_process_importer_host.cc",
    "//luxxle/browser/importer/luxxle_in_process_importer_bridge.cc",
    "//luxxle/browser/importer/luxxle_in_process_importer_bridge.h",
  ]
  if (enable_extensions) {
    luxxle_browser_importer_impl_sources += [
      "//luxxle/browser/importer/extensions_import_helpers.cc",
      "//luxxle/browser/importer/extensions_import_helpers.h",
    ]
    luxxle_browser_importer_impl_deps += [
      "//luxxle/common/importer",
      "//chrome/browser/extensions",
      # Commented out: removed components dependency - using Chromium defaults instead
      # "//components/value_store",
      "//extensions/browser",
      "//extensions/common:common_constants",
    ]
  }
  luxxle_browser_importer_impl_deps += [
    "//base",
    "//luxxle/app:luxxle_generated_resources_grit_grit",
    "//luxxle/browser/importer",
    "//luxxle/common/importer:interfaces",
    "//content/public/browser",
    "//extensions/buildflags",
    "//mojo/public/cpp/bindings:bindings",
  ]
}
