import("//chrome/installer/util/BUILD.gn")

generate_embedded_i18n("generate_strings") {
  visibility = [
    ":strings",
    ":with_no_strings",
  ]
  extractor_datafile =
      "//luxxle/installer/util/prebuild/create_installer_string_rc.py"

  grdfile_folder = "//chrome/app/"
  grdfile_name = "${branding_path_product}_strings"
  xtb_relative_path = "resources"
  grd_files_info = [ [
        grdfile_folder,
        grdfile_name,
        xtb_relative_path,
        default_embedded_i18_locales,
      ] ]

  output_file_name_base = "installer_util_strings"

  branding = "luxxle"
}