# Copyright (c) 2024 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//luxxle/common/extensions/api/api_sources.gni")
import("//tools/json_schema_compiler/json_schema_api.gni")

function_registration("generated_api_registration") {
  sources = brave_extensions_api_schema_sources
  impl_dir = "//luxxle/browser/extensions/api/"
  bundle_name = "Brave"
  root_namespace = brave_extensions_api_root_namespace

  deps = [
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/brave_ads/core/mojom",
    # Commented out: removed components dependency - using Chromium defaults instead
    # "//luxxle/components/brave_rewards/core/mojom",
    "//extensions/browser",
    "//extensions/common",
  ]
}
