# Copyright (c) 2024 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

luxxle_ui_color_sources = []
luxxle_ui_color_public_deps = [ "//luxxle/ui/color:nala_color_id" ]

luxxle_ui_color_mixer_sources = []
luxxle_ui_color_mixer_public_deps = [ "//luxxle/ui/color:luxxle_color_mixers" ]
