# Copyright (c) 2023 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//luxxle/build/config.gni")
import("//build/config/ui.gni")

declare_args() {
  luxxle_services_production_domain = "api.luxxle.com"
  luxxle_services_staging_domain = "api-staging.luxxle.com"
  luxxle_services_dev_domain = "api-dev.luxxle.com"
}
