# Copyright (c) 2023 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//build/buildflag_header.gni")
import("buildflags.gni")

source_set("luxxle_domains") {
  sources = [
    "service_domains.cc",
    "service_domains.h",
  ]

  deps = [
    ":buildflags",
    "//base",
  ]
}

buildflag_header("buildflags") {
  header = "buildflags.h"
  flags = [
    "LUXXLE_SERVICES_PRODUCTION_DOMAIN=\"$luxxle_services_production_domain\"",
    "LUXXLE_SERVICES_STAGING_DOMAIN=\"$luxxle_services_staging_domain\"",
    "LUXXLE_SERVICES_DEV_DOMAIN=\"$luxxle_services_dev_domain\"",
  ]

  # Consumers should use the luxxle_domains helper functions.
  visibility = [ ":*" ]
}

source_set("unit_tests") {
  testonly = true

  sources = [ "service_domains_unittest.cc" ]

  deps = [
    ":luxxle_domains",
    ":buildflags",
    "//base",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
