# Copyright (c) 2024 The Luxxle Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

# This target should be included into all Luxxle test binaries to make
# base::CurrentTestVendor::Get() return kLuxxle.
source_set("test_vendor_is_luxxle") {
  testonly = true
  sources = [ "test_vendor_is_luxxle.cc" ]
  deps = [ "//base/test:test_support" ]
}
